name: 'Sample Workflow1'
id: 'wf2'
primary-key:
  - key: 'key2'
    input: '$$body.ID'
authorizer:
  type: jwt
  key: Authorization
  input: Header
  secret: 'Ssh!! My Secret'

cors:
  allow-origin: '*'
  allow-method: '*'

steps:
  - id: step1
    type: api
    authorize: true
    # endpoint: 'https://postman-echo.com/get?foo1=$$body.data.0.key&foo2=$$testStep.ref.key'
    endpoint: 'http://localhost:1200/$$testStep.ref.key'
    method: POST
    payload:
      staticdata:
        mykey: 'my-value'
      dynamicdata: $$body
    include-headers: true
    custom-headers:
      api-key: 10
    async: false
    delay: 500ms
    break: true
    timeout: 5s

  - id: step2
    name: 'my first step'
    type: logic
    runtime: 'python'
    exe-path: '/tmp/path'
    handler: main
    async: true
    delay: 500ms
    timeout: 15ms
    next-step: 'step2'
    payload: $$body
    pre-condition:
      - if:
        when: 'abcd == efgh'
        then:
          goto: step3
      - else-if:
      - else:
    post-condition:
    break: true
    error:
      retry: true
      goto:
