name: 'Sample Workflow1'
id: 'wf1'
primary-key:
  - key: 'key2'
    input: '$$body.ID'
authorizer:
  type: jwt
  key: Authorization
  input: Header
  secret: 'Ssh!! My Secret'

cors:
  allow-origin: '*'
  allow-method: '*'

steps:
  - id: step1
    type: api
    authorize: true
    endpoint: 'http://api.plos.org/search?q=title:$$queryParams.title'
    method: GET
    payload: $$body
    include-headers: true
    custom-headers:
      api-key: 10
    async: true
    delay: 500ms
    break: true
    timeout: 15ms

  - id: step2
    name: 'my first step'
    type: logic
    runtime: 'python'
    exe-path: '/tmp/path'
    handler: main
    async: true
    delay: 500ms
    timeout: 15ms
    next-step: 'step2'
    pre-condition:
      - if:
        when: 'abcd == efgh'
        then:
          goto: step3
      - else-if:
      - else:
    post-condition:
    break: true
    error:
      retry: true
      goto:
